server:
  port: 8080

spring:
  application:
    name: smart-deploy-monitor
  
  # Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/smart_deploy_monitor
    username: postgres
    password: Root@123
    driver-class-name: org.postgresql.Driver
  
  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: create-drop  # Create tables automatically for development
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    open-in-view: false
  
  # Flyway Configuration (disabled for now)
  flyway:
    enabled: false
  
  # Redis Configuration
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
  
  # Elasticsearch Configuration
  elasticsearch:
    rest:
      uris: http://localhost:9200
      connection-timeout: 1s
      read-timeout: 30s

# OpenAPI/Swagger Configuration
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    tryItOutEnabled: true

# GraphQL Configuration
spring:
  graphql:
    graphiql:
      enabled: true
      path: /graphiql
    path: /graphql
    schema:
      location: classpath:graphql/
    cors:
      allowed-origins: "*"
      allowed-methods: "GET,POST,OPTIONS"
      allowed-headers: "*"

# gRPC Configuration (simplified for Level 3)
# grpc:
#   server:
#     port: 9090
#     enable-reflection: true
  show-actuator: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,env,beans,configprops
  endpoint:
    health:
      show-details: always
      show-components: always
    prometheus:
      enabled: true
    metrics:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        http.server.requests: true
        demo.response.time: true
      percentiles:
        http.server.requests: 0.5, 0.95, 0.99
        demo.response.time: 0.5, 0.95, 0.99

logging:
  level:
    com.upskilling.smartdeploymonitor: INFO
    org.springframework.web: INFO
    org.springframework.scheduling: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/smart-deploy-monitor.log

# Qdrant Configuration
qdrant:
  host: localhost
  port: 6333

# Keycloak Configuration
keycloak:
  realm: smart-deploy-monitor
  auth-server-url: http://localhost:8081
  ssl-required: none
  resource: smart-deploy-monitor-client
  credentials:
    secret: your-client-secret-here
  use-resource-role-mappings: true
  bearer-only: false