# Smart Deploy Monitor Application Configuration
# Demonstrates Observability + CI/CD integration
spring:
  application:
    name: smart-deploy-monitor
  profiles:
    active: dev

# Server Configuration
server:
  port: 8080
  servlet:
    context-path: /api

# Actuator Configuration for Observability
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,env,configprops
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      show-components: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}
      environment: ${spring.profiles.active}

# Logging Configuration for Observability
logging:
  level:
    com.upskilling.smartdeploymonitor: INFO
    org.springframework.web: INFO
    org.springframework.boot.actuate: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/smart-deploy-monitor.log

# Application Info for Observability
info:
  app:
    name: Smart Deploy Monitor
    description: Spring Boot application demonstrating CI/CD and Observability
    version: 1.0.0
    environment: ${spring.profiles.active}
  build:
    artifact: ${project.artifactId}
    version: ${project.version}

# Advanced Features Configuration
app:
  features:
    cache:
      enabled: true
      ttl: 300 # 5 minutes
    database:
      simulation:
        enabled: true
        initial-users: 2
    external-api:
      simulation:
        enabled: true
        failure-rate: 0.1 # 10% failure rate
        response-time:
          min: 100
          max: 600
