version: '3.8'

services:
  # Redis for TTL-based caching
  redis:
    image: redis:7-alpine
    container_name: smart-deploy-redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - smart-deploy-network

  # Elasticsearch for search/filter operations
  elasticsearch:
    image: elasticsearch:8.11.0
    container_name: smart-deploy-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - smart-deploy-network

  # Qdrant for vector operations
  qdrant:
    image: qdrant/qdrant:latest
    container_name: smart-deploy-qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - smart-deploy-network

volumes:
  redis_data:
  elasticsearch_data:
  qdrant_data:

networks:
  smart-deploy-network:
    driver: bridge