name: Smart Deploy Monitor CI/CD

on:
  push:
    branches: [ main ]
    paths: 
      - 'practices/observability-cicd/smart-deploy-monitor/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'practices/observability-cicd/smart-deploy-monitor/**'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    
    - name: Run tests
      run: cd practices/observability-cicd/smart-deploy-monitor && mvn clean test
    
    - name: Build application
      run: cd practices/observability-cicd/smart-deploy-monitor && mvn clean package -DskipTests
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: smart-deploy-monitor-jar
        path: practices/observability-cicd/smart-deploy-monitor/target/*.jar